language: python
python:
  - '3.6'

matrix:
  fast_finish: true

notifications:
  email: false

install:
  - sudo apt-get -qq update
  - sudo apt-get install libmagickwand-dev  # required by Wand
  - sudo rm -rf /etc/ImageMagick-6/policy.xml  # HazyResearch/fonduer#170
  - make dev
  - pip install coveralls

before_script:
  - make check
  - cd tests/input/
  - ./download_vision_model.sh
  - cd ../../

script:
  - coverage run --source=pdftotree -m pytest tests -v -rsXx
  - python setup.py -q install
  - pdftotree tests/input/112823.pdf

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lukehsiao
  password:
    secure: BYpjjgOk4RZohLStyqIlP2UYCOgG76zykvxfNp2wP6ewb5Sf7HPn4BDMst1FCCPBm6ekLlIRAdZJFJp/+IPyakkWeeT/FPM6oqZxeFsa6o0aFdxzHU4qA4aEb03MUpj+7lcQ9WS8x88yyLEjxQuAN31eHNAhVWUfl59ek7Jg2zJ+m/xUmKBrVjPTkrO/PNzJ3AkcKieB/27XM6CVBfi0a+JVBrZUM+nT6WtVAwp9porcOXRj6mma7vzviyo1pIhqQkruHWDeS+iZ890KuKGwRv0QWWz5w04GVC8Yg0bTc/7kY48wHjOGiSajahdM3HjhQ5ekLwP/iUdU6ICTjfj4fHt4EJhv2TOd/P9A39Sp6Q0kUQkhp8/gyz/xBt0DdMx6XXMrUsUkP/tv7aCyRvRmm6mXrpOfODEbecbXTLG6dCdha4RluWfp5cq3Q2iYclskv0o2bwXaOvr6a7fAZO2mlKsZ/EaCJPGhKRbLe03OYo9RWvd9tPgeSrw2kYmOyc3jGuSRIBBC6PFBggK8wBnznkdYq22sI7j8xCqk8Fi/sQ7Hg1PyCIJAWQQgRUJEcMmY8eW30H7dObypORILxijUm50VoPTFcweCbM4kRTSC4+rwZOzTtH4dLGser8i4vg09JjO2iXNyDfFCaeZctTDX+pjTnEqX5wlz6zYhZUgJtwg=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    python: '3.6' # Only deploy once from the latest version tested

