#! /bin/bash

if [ $# -lt 2 ]
  then echo -e "Please provide an output directory and an input PDF. Example: pdf2hocr ./ocrd ~/Downloads/document.pdf"
  exit 1
fi

mkdir -p $1
mkdir -p $1/png
mkdir -p $1/tesseract
mkdir -p $1/annotated
mkdir -p $1/tables

gs -dBATCH -dNOPAUSE -sDEVICE=png16m -dGraphicsAlphaBits=4 -dTextAlphaBits=4 -r600 -sOutputFile="$1/png/page_%d.png" $2

PAGES=$(ls $1/png | wc -l | bc)

while [ $PAGES -gt 0 ]; do
  tesseract $1/png/page_$PAGES.png $1/tesseract/page_$PAGES.html hocr
  mv $1/tesseract/page_$PAGES.html.hocr $1/tesseract/page_$PAGES.html
  python annotate.py $1/tesseract/page_$PAGES.html $1/annotated/page_$PAGES.png
  let PAGES-=1
done

cp $2 $1/orig.pdf
